//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfernoBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfernoBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExtForm_Shape {
            get {
                object obj = ResourceManager.GetObject("ExtForm_Shape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Inferno_Browser_Logo__Transparent_ {
            get {
                object obj = ResourceManager.GetObject("Inferno_Browser_Logo__Transparent_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Inferno_Logo_PNG {
            get {
                object obj = ResourceManager.GetObject("Inferno_Logo_PNG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;Inferno_Style.css&quot;&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=Aladin&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Main Page&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;logo&quot;&gt;
        ///        &lt;img id=&quot;inferno-logo&quot; src=&quot;Inferno Browser Logo (Transparent).png&quot;&gt;
        ///    &lt;/div&gt;
        ///    &lt;div id=&quot;name&quot;&gt;
        ///        InfernoBrowser
        ///    &lt;/div&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Inferno_Main_Page {
            get {
                return ResourceManager.GetString("Inferno_Main_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    background-image: url(Inferno\ Main\ Page\ BG.png);
        ///}
        ///
        ///#logo {
        ///    display: flex;
        ///    margin-left: -50px;
        ///    justify-content: center;
        ///}
        ///
        ///#inferno-logo {
        ///    width: 250px;
        ///    height: 350px;
        ///}
        ///
        ///#name {
        ///    font-family: &apos;Aladin&apos;;
        ///    display: flex;
        ///    justify-content: center;
        ///    color: #d80000;
        ///    font-size: 110px;
        ///    margin-left: -10px;
        ///    margin-top: -20px;
        ///    text-shadow: 2px 2px #770000e8;
        ///    
        ///}.
        /// </summary>
        internal static string Inferno_Style {
            get {
                return ResourceManager.GetString("Inferno_Style", resourceCulture);
            }
        }
    }
}
